### ISSUE TITLE
设定更新时间为“永不更新”以后仍会自动更新

### ISSUE THREAD

**Issue by upsuper** [moeoverflow/PixivForMuzeiPlus#1]
因为某些原因，我不太希望壁纸自己换掉（主要还是对推荐质量不太满意，可能跟收藏数太少也有关），于是将更新时间设置为了“永不更新”。

在大多数时候是不会更新了，但当我想要改的时候，打开Muzei去翻，翻到满意的退出以后背景保留了。可几个小时之后再看手机，就发现它自动更新了一次换掉了我刚刚选定的图片……然后我不得不再翻一次挑一张满意的。不过这样之后就不会再被自动更新掉了。

**Comment by democyann** [comment]
嗯嗯~ 这个问题是由于修改了设置后必须执行一次加载图片的操作才会生效改配置，人家改一下喵~

**Comment by democyann** [comment]
目前1.2.1版本已经解决了这个问题，请从 Google Play 更新最新版本。
